<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net9.0</TargetFrameworks>
        <Nullable>enable</Nullable>
        <LangVersion>13.0</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>HamsterWheel.HLinq</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.Memory" />
    </ItemGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <DefineConstants>TRACE;HLINQ</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DefineConstants>TRACE;HLINQ</DefineConstants>
    </PropertyGroup>

</Project>
