image: mcr.microsoft.com/dotnet/sdk:9.0
services:
  - name: postgres
    variables:
      POSTGRES_DB: Demo
      POSTGRES_PASSWORD: outflank-outage-undoing

variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: ''

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json'
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*'
    - '$NUGET_PACKAGES_DIRECTORY'
  policy: pull-push

before_script:
  - 'dotnet restore HLinq.slnx --packages $NUGET_PACKAGES_DIRECTORY'

build:
  stage: build
  script:
    - 'dotnet build HLinq.slnx --no-restore'

tests:
  stage: test
  script:
    - 'dotnet test HLinq.slnx --logger:"junit;LogFileName=$SOURCE_CODE_PATH/rspec.xml"'
  artifacts:
    when: always
    paths:
      - rspec.xml
    reports:
      junit:
        - rspec.xml

package:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  script: echo "Define your deployment script!"
  environment: production