image: mcr.microsoft.com/dotnet/sdk:9.0

variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: ''
  TEST_CODE_PATH: '/builds/hamster-wheel/hlinq/test'
  FF_NETWORK_PER_BUILD: "true"

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json'
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*'
    - '$NUGET_PACKAGES_DIRECTORY'
  policy: pull-push

before_script:
  # Configure GitLab package registry as a NuGet source
  - 'dotnet nuget add source "${CI_API_V4_URL}/groups/69/-/packages/nuget/index.json" --name group --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text'
  - 'dotnet restore HLinq.slnx --packages $NUGET_PACKAGES_DIRECTORY'

build:
  stage: build
  script:
    - 'dotnet build --no-restore'

tests:
  services:
    - name: postgres
  variables:
    FF_NETWORK_PER_BUILD: 1
    POSTGRES_PASSWORD: outflank-outage-undoing
    POSTGRES_DB: Demo
    POSTGRES_HOST: postgres
  stage: test
  script:
    - 'dotnet tool install --local dotnet-coverage --create-manifest-if-needed'
    - 'dotnet tool install --local dotnet-reportgenerator-globaltool'
    - 'dotnet test --no-restore /p:CollectCoverage=true --collect:"XPlat Code Coverage" --logger:"junit;LogFileName=rspec.xml" /p:Exclude="[HamsterWheel.HLinq.Demo*]*"'
    - 'dotnet tool run dotnet-coverage merge -o $TEST_CODE_PATH/merged.cobertura.xml -f cobertura $TEST_CODE_PATH/**/coverage.cobertura.xml'
    - 'dotnet tool run reportgenerator -reports:$TEST_CODE_PATH/merged.cobertura.xml -targetdir:coveragereport -reporttypes:JsonSummary'
    - 'cat coveragereport/Summary.json | grep linecoverage'
  coverage: '/linecoverage":\s(\d+?),/'
  artifacts:
    when: always
    paths:
      - $TEST_CODE_PATH/**/rspec.xml
    reports:
      junit:
        - $TEST_CODE_PATH/**/rspec.xml
      coverage_report:
        coverage_format: cobertura
        path: $TEST_CODE_PATH/merged.cobertura.xml

package-alpha:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "alpha"
  script:
    - dotnet pack -c Release --version-suffix $CI_COMMIT_BRANCH-$CI_JOB_ID
    # Configure GitLab package registry as a NuGet source
    - dotnet nuget add source "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    # Push the package to the project's package registry
    - dotnet nuget push "src/**/bin/Release/*.nupkg" --source gitlab
    - wget https://g.np0.pl/hamster-wheel/hlinq/-/badges/release.svg
  environment: staging

package:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  script:
    - dotnet pack HLinq.slnx -c Release
    # Configure GitLab package registry as a NuGet source
    - dotnet nuget add source "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    # Push the package to the project's package registry
    - dotnet nuget push "src/**/bin/Release/*.nupkg" --source gitlab
  environment: production