<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <OutputType>Library</OutputType>
        <RootNamespace>HamsterWheel.HLinq.Client</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\HamsterWheel.HLinq\HamsterWheel.HLinq.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Include="..\HamsterWheel.HLinq\EFDbFunctionsMatcher.cs">
        <Link>EFDbFunctionsMatcher.cs</Link>
      </Compile>
    </ItemGroup>

</Project>
