@HostAddress = http://localhost:5087

###

GET {{HostAddress}}/demo/memory?orderBy[x.name].take[1]
Accept: application/json

###
GET {{HostAddress}}/demo/db?where[John==x.firstName]
Accept: application/json

###
GET {{HostAddress}}/demo/db?where[x.firstName==John Doe]
Accept: application/json

###
GET {{HostAddress}}/demo/random
Accept: application/json

###
GET {{HostAddress}}/demo/controller/memory?take[1]
Accept: application/json

###
