<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>HamsterWheel.HLinq.UnitTests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\HamsterWheel.HLinq.Abstractions\HamsterWheel.HLinq.Abstractions.csproj">
            <SetTargetFramework>TargetFramework=netstandard2.0</SetTargetFramework>
        </ProjectReference>
    </ItemGroup>

    <ItemGroup>
      <Compile Include="..\HamsterWheel.HLinq.UnitTests\ValueConverters\BaseConfigurableValueConverterUnitTests.cs">
        <Link>ValueConverters\BaseConfigurableValueConverterUnitTests.cs</Link>
      </Compile>
      <Compile Include="..\HamsterWheel.HLinq.UnitTests\ValueConverters\BaseValueConverterUnitTests.cs">
        <Link>ValueConverters\BaseValueConverterUnitTests.cs</Link>
      </Compile>
    </ItemGroup>

</Project>
