<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>HamsterWheel.HLinq</RootNamespace>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <DefineConstants>TRACE;HLINQ</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DefineConstants>TRACE;HLINQ</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\HamsterWheel.HLinq.Abstractions\HamsterWheel.HLinq.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="DynamicAnonymousType" Version="1.0.6" />
        <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.2" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Builders\ConditionalLogicalOperationConverter.Exceptions.cs">
        <DependentUpon>ConditionalLogicalOperationConverter.cs</DependentUpon>
      </Compile>
      <Compile Update="Builders\ConverterFactory.Exceptions.cs">
        <DependentUpon>ConverterFactory.cs</DependentUpon>
      </Compile>
      <Compile Update="Tree\Filter\Condition.Exceptions.cs">
        <DependentUpon>Condition.cs</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
